#!/bin/sh
 ssh ec2-user@54.172.130.156 <<EOF
 cd /home/ec2-user/tempfiles
 git pull
 npm install --production 
 pm2 restart all
  ssh ec2-user@34.229.18.122 <<EOF
  cd /home/ec2-user/tempfiles
  git pull
  npm install --production 
  pm2 restart all
 exit
exit
EOF
 EOF
